### ISSUE TITLE
Spells are not rolling

### ISSUE THREAD

**Issue by unclejayrazz** [mjeffw/nordlond-bestiary-public#4] opened 2022-09-08 18:14 UTC
So when I try to click on spells on the Nordlond Beast sheet, it doesn't work. I've uninstalled and reinstalled the Nordlond Bestiary to make sure I have the latest version and the issue still persists.

**Comment by mjeffw** [comment] 2022-09-09 11:16
Are you on Forge? Or self hosting?

**Comment by unclejayrazz** [comment] 2022-09-09 11:30
I use a cloud server on atlantic.net

**Comment by mjeffw** [comment] 2022-09-10 20:36
If you have the ability to run Foundry locally, it would help me confirm what I suspect is the culprit here. Ideally, you could set up a Foundry instance on your local computer and configure it with the same modules and versions. See if the problem is reproduced. My suspicion is that this problem only appears when running on a remote server.

**Comment by unclejayrazz** [comment] 2022-09-11 01:02
I just installed FoundryVTT locally on my desktop. I installed the GCA along with Nordlond Bestiary. I imported a character sheet and just checked. It does the same thing. It also does it when I just click on one of the Bestiary entries as well.
![nordlondbestiarytest](https://user-images.githubusercontent.com/25803586/189507054-56ff5929-4627-4fe4-9a20-512cd1222f84.png)

**Comment by mjeffw** [comment] 2022-09-11 19:22
Well, the image is what happens when you right-click a spell. I do see that left-clicking a spell isn't working and I can see problem. Working on it.

**Comment by mjeffw** [comment] 2022-09-11 20:37
Fixed in version 1.0.8. **_This is still FoundryVTT version 9 compatible -- it is incompatible with Foundry v10!_**

V10 compatibility is coming shortly.

**Closed as completed by mjeffw** 2022-09-11 20:37 UTC
